const Menu = [
    {
        id: 1,
        image: "https://cdn.pixabay.com/photo/2017/03/13/13/39/pancakes-2139844_1280.jpg",
        name: "Pancakes",
        category: "Breakfast",
        price: "$2.95",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },
    {
        id: 2,
        image: "https://cdn.pixabay.com/photo/2016/08/12/16/01/cake-1589012_1280.jpg",
        name: "Muffies",
        category: "Breakfast",
        price: "$1.95",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },
    {
        id: 3,
        image: "https://cdn.pixabay.com/photo/2017/08/07/07/18/table-2600954_1280.jpg",
        name: "Fruit Bowl",
        category: "Breakfast",
        price: "$13.95",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },
    {
        id: 4,
        image: "https://cdn.pixabay.com/photo/2016/11/18/19/00/bread-1836411_1280.jpg",
        name: "Fry Eggs",
        category: "Breakfast",
        price: "$2.75",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },
    {
        id: 5,
        image: "https://cdn.pixabay.com/photo/2020/03/07/05/18/coffee-4908764_1280.jpg",
        name: "Coffee",
        category: "Breakfast",
        price: "$2.95",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },
    {
        id: 6,
        image: "https://cdn.pixabay.com/photo/2016/06/26/22/46/india-1481504_1280.jpg",
        name: "Veg Thali",
        category: "Main Course",
        price: "$20.95",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },
    {
        id: 7,
        image: "https://cdn.pixabay.com/photo/2023/07/11/05/23/ai-generated-8119616_1280.jpg",
        name: "Chicken Biryani",
        category: "Main Course",
        price: "$2.95",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },
    {
        id: 8,
        image: "https://cdn.pixabay.com/photo/2020/05/04/12/13/indian-food-5128940_1280.jpg",
        name: "Non-Veg Thali",
        category: "Main Course",
        price: "$2.95",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },
    {
        id: 9,
        image: "https://cdn.pixabay.com/photo/2015/09/09/18/25/food-932348_1280.jpg",
        name: "Chicken Veggies",
        category: "Main Course",
        price: "$2.95",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },
    {
        id: 10,
        image: "https://cdn.pixabay.com/photo/2022/06/02/18/21/ramen-7238664_1280.jpg",
        name: "Ramen Noodles",
        category: "Main Course",
        price: "$2.95",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },
    {
        id: 11,
        image: "https://cdn.pixabay.com/photo/2023/04/04/14/53/samosa-7899498_1280.jpg",
        name: "Samosa",
        category: "Veg Starter",
        price: "$2.95",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },
    {
        id: 12,
        image: "https://cdn.pixabay.com/photo/2020/05/04/12/17/frankie-5128958_1280.jpg",
        name: "Frankie Roll",
        category: "Veg Starter",
        price: "$2.95",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },
    {
        id: 13,
        image: "https://cdn.pixabay.com/photo/2022/04/01/10/20/panipuri-7104501_1280.jpg",
        name: "Pani Puri",
        category: "Veg Starter",
        price: "$2.95",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },
    {
        id: 14,
        image: "https://cdn.pixabay.com/photo/2015/02/27/07/50/grill-651784_1280.jpg",
        name: "Chicken Wings",
        category: "Non-Veg Starter",
        price: "$2.95",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },
    {
        id: 15,
        image: "https://cdn.pixabay.com/photo/2020/01/05/00/38/chicken-noodle-soup-4742070_1280.jpg",
        name: "Chicken Soups",
        category: "Non-Veg Starter",
        price: "$2.95",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },
    {
        id: 16,
        image: "https://cdn.pixabay.com/photo/2023/05/09/15/52/ai-generated-7981848_1280.jpg",
        name: "Chic Tenders",
        category: "Non-Veg Starter",
        price: "$2.95",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },
    {
        id: 17,
        image: "https://cdn.pixabay.com/photo/2017/03/30/15/46/churros-2188869_1280.jpg",
        name: "Chuuros",
        category: "Dessert",
        price: "$2.95",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },
    {
        id: 18,
        image: "https://cdn.pixabay.com/photo/2018/05/10/22/42/ice-cream-3389010_1280.jpg",
        name: "Ice Cream",
        category: "Dessert",
        price: "$2.95",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },
    {
        id: 19,
        image: "https://cdn.pixabay.com/photo/2022/05/22/13/36/raspberries-7213407_1280.jpg",
        name: "Moose",
        category: "Dessert",
        price: "$2.95",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },
    {
        id: 20,
        image: "https://cdn.pixabay.com/photo/2019/09/02/06/22/chocolate-cake-4446608_1280.jpg",
        name: "Cakes",
        category: "Dessert",
        price: "$2.95",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },
    {
        id: 21,
        image: "https://rakskitchen.net/wp-content/uploads/2013/12/11247326833_0f99d56b4f_z.jpg",
        name: "South Indian",
        category: "Breakfast",
        price: "$2.95",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },
    {
        id: 22,
        image: "https://img.mensxp.com/media/content/2023/Feb/indian-breakfast-2_63da24b3f3242.jpeg",
        name: "Parathas",
        category: "Breakfast",
        price: "$2.95",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },
    {
        id: 23,
        image: "https://ministryofcurry.com/wp-content/uploads/2020/05/pohe-2.jpg",
        name: "Kanda Poha",
        category: "Breakfast",
        price: "$2.95",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },
    {
        id: 24,
        image: "https://www.tasteofhome.com/wp-content/uploads/2023/02/GettyImages-1166167738-e1676393874715.jpg?fit=700%2C700",
        name: "Palak Paneer",
        category: "Main Course",
        price: "$2.95",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },
    {
        id: 25,
        image: "https://spoonuniversity.com/wp-content/uploads/sites/214/2016/03/Chole-Bhatura-1024x896.jpg",
        name: "Chola Puri",
        category: "Main Course",
        price: "$2.95",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },
    {
        id: 26,
        image: "https://images.immediate.co.uk/production/volatile/sites/30/2022/10/Simple-mushroom-curry-26e3403.jpg?quality=90&resize=556,505",
        name: "Butter Chicken",
        category: "Main Course",
        price: "$2.95",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },
    {
        id: 27,
        image: "https://cdn.shopify.com/s/files/1/0510/9556/8581/files/coconut_barfi_480x480.jpg?v=1690796216",
        name: "Coconut Barfi",
        category: "Dessert",
        price: "$2.95",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },
    {
        id: 28,
        image: "https://www.tasteofhome.com/wp-content/uploads/2021/01/sandesh-indian-dessert.jpg?fit=700%2C700",
        name: "Rasmalai",
        category: "Dessert",
        price: "$2.95",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, repellendus?",
    },

];

export default Menu;